name: example
environment:
  sdk: any
dependencies:
  mongo_dart: "0.3.1"
  bson: '^0.3.0'
  crypto: '>=0.9.2 <3.0.0'
  logging: '>=0.8.0 <2.0.0'
  mongo_dart_query: '^0.3.0'
  collection: ">=1.4.0 <2.0.0"
  path: ">=1.3.0"
  uuid: "^0.5.0"
